services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: teencare
    ports:
      - "5432:5432"
    volumes:
      - ./docker/db:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/teencare
    volumes:
      - .:/app
    depends_on:
      - db
    # Tự động hóa: cài đặt thư viện, tạo client, đồng bộ cấu trúc DB và bật server
    command: sh -c "yarn install && npx prisma generate && npx prisma db push --accept-data-loss && yarn dev"
